org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=33
android.bundle.enableUncompressedNativeLibs=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.nonFinalResIds=false