apply plugin: 'com.android.application'
apply plugin: 'top.niunaijun.blackobfuscator'

android {
    compileSdkVersion 33
    buildToolsVersion "34.0.0"
    
    packagingOptions {
        jniLibs {
            useLegacyPackaging = true
            resources.excludes.add("META-INF/*")
        }
    }
    
    lintOptions {
        disable 'MissingTranslation'
        checkReleaseBuilds false
    }
    
    defaultConfig {
        applicationId "com.flyvpnpro.official"
		minSdkVersion 21
        targetSdkVersion 33
        versionCode 10
        versionName "3.0.7"
        multiDexEnabled true
        
        vectorDrawables {
            useSupportLibrary true
        }      
	}
    
    BlackObfuscator {
       enabled true
       depth 2
    // The classes which need to be obfuscated
       obfClass = ["com.flyvpnpro.main", "com.flyvpnpro.second"]
    // It will not obfuscate the classes that in blackClass
       blackClass = ["top.niunaijun.black"]
    }
    
    signingConfigs {
        release {
            storeFile file("../key/flyvpnpro.official78.jks")
            storePassword 'flyvpnpro'
            keyAlias 'flyvpnpro.official'
            keyPassword 'flyvpnpro'
            v1SigningEnabled true
            v2SigningEnabled true
        }
        debug {
            storeFile file("../key/flyvpnpro.official78.jks")
            storePassword 'flyvpnpro'
            keyAlias 'flyvpnpro.official'
            keyPassword 'flyvpnpro'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            zipAlignEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
            ndk {
                abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64'
            }
        }
        
        debug {
            minifyEnabled false
            shrinkResources false
            zipAlignEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
            ndk {
                abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64'
            }
        }
    }   
        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_8
            targetCompatibility JavaVersion.VERSION_1_8    
        
    }
    namespace 'com.flyvpnpro.official'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
    implementation project(':showcaseviewlib')
	implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.annotation:annotation:1.1.0'
    implementation 'com.pnikosis:materialish-progress:1.7'
    implementation 'com.sdsmdg.tastytoast:tastytoast:0.1.1'
    implementation 'androidx.recyclerview:recyclerview:1.2.1'
	implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.appcompat:appcompat:1.6.0'
    implementation 'androidx.preference:preference:1.2.0'
    implementation 'com.google.android.play:core:1.10.3'
	implementation 'com.google.android.material:material:1.7.0'
	implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.google.android.gms:play-services-ads:21.4.0'
    implementation 'com.google.firebase:firebase-analytics'
    implementation platform('com.google.firebase:firebase-bom:31.1.1')
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
    implementation 'com.flurry.android:analytics:14.0.0@aar'
    implementation 'net.i2p.crypto:eddsa:0.3.0'
    implementation 'org.connectbot.jbcrypt:jbcrypt:1.0.0'
	implementation 'com.github.kimchangyoun:rootbeerFresh:0.0.10'
    implementation "androidx.lifecycle:lifecycle-viewmodel:2.5.1"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.5.1"
    implementation 'com.github.javiersantos:PiracyChecker:1.2.8'
    
}
